#!/usr/bin/env bash
# Configures an Ubuntu server with custom localhost and facebook.com IP mappings

cp /etc/hosts ~/hosts.backup
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
