#!/usr/bin/env bash
# Configures an Ubuntu server with custom localhost and facebook.com IP mappings

cp /etc/hosts ~/hosts.backup
grep -v 'localhost\|facebook.com' /etc/hosts > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
sudo cp /tmp/hosts.tmp /etc/hosts
rm /tmp/hosts.tmp
